### ISSUE TITLE
Docker'ize project to make working on project easier

### ISSUE THREAD

**Issue by kristians-kuhta** [kristians-kuhta/justicantus#52]
Currently, the project is not as easy to set up for local development as it could be.

Let's consider using Docker to reduce dev. environment setup to something like setting environment variables in the `.env` file and running
```
docker-compose up
```

**Comment by AntonBangoura** [comment]
Hello, is this enhancement still needed?

**Comment by kristians-kuhta** [comment]
Hey, sorry @AntonBangoura , but I will not be developing or maintaining this project further.
